const officeQuotes = [
    'Would I rather be feared or loved? Easy. Both. I want people to be afraid of how much they love me. —Michael Scott.',
    "Identity theft is not a joke, Jim! Millions of families suffer every year. - Dwight Schrute", 
    "I’m not superstitious, but I am a little stitious. - Michael Scott",
    "I’ve been involved in a number of cults, both a leader and a follower. You have more fun as a follower, but you make more money as a leader. —Creed Bratton",
    "Life is short. Drive fast and leave a sexy corpse. That’s one of my mottos. —Stanley Hudson.",
    "Bears, beats, Battle Star Galactica. - Jim Halpert",
    "Me think, why waste time say lot word when few word do trick. - Kevin Malone",
    "Dwight mercy-killed Angela’s cat. - Pam Beesley",
    "I run a small fake ID company from my car with a laminating machine that I swiped from the Sheriff’s station. - Creed Bratton",
    "Today, smoking is going to save lives. - Dwight Schrute",
    "That's what she said. - Michael Scott",
    "Life is short. Drive fast and leave a sexy corpse. That’s one of my mottos. - Stanley Hudson.",
    "Oh, you’re paying way too much for worms. Who’s your worm guy? - Creed Bratton",
    "I have been trying to get on jury duty every year since I was 18 years old. To get to go sit it in an air-conditioned room, downtown, judging people, while my lunch is paid for… that is the life. - Stanley Hudson",
    "Nobody steals from Creed Bratton and gets away with it. The last person to do this disappeared. His name? Creed Bratton. - Creed Bratton",
    "Why are you the way that you are? Honestly, every time I try to do something fun, or exciting, you make it… not that way. I hate… so much about the things that you choose to be. - Michael Scott",
    "Rit-dit-dit-do-doo! - Andy Bernard",
    "Bob Vance, Vance Refrigeration. - Bob Vance",
    "One day Michael came in and complained about a speed bump on the highway. I wonder who he ran over then. - Jim Halpert",
    "I wish there was a way to know you’re in the good old days, before you’ve actually left them. - Andy Bernard",
    "In the Schrute family, the youngest child raises the others. I've been raising children since I was a baby. - Dwight Schrute",
    "Every so often, Jim dies of boredom. - Pam Beesley",
    "Saw Inception. Or at least I dreamt I did. - Micheal Scott",
    "Did I stutter? - Stanley Hudson",
    "I have a lot of questions. Number one, how dare you? - Kelly Kapoor",
    "This is a dream that I've had...since lunch...and I'm not giving it up now. - Michael Scott",
    "I am fast. To give you a reference point. I'm somewhere between a snake and a mongoose. And a panther. - Dwight Schrute",
    "Oh my God it's happening! Everybody stay calm. Stay f*cking calm! -Michael Scott",
    "Whenever I'm about to do something, I think, 'Would an idiot do that?' And if they would, I do not do that thing. - Dwight Schrute",
    "There's something about an underdog that really inspires the unexceptional. - Robert California",
    "Who is Justice Beaver? - Dwight Schrute"
  ];

export { officeQuotes };
